
import java.awt.Color;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahadahmed
 */
public class ColorGame extends javax.swing.JPanel {

	/**
	 * Creates new form ColorGame
	 */
	private String colors[] = {"RED", "BLUE", "GREEN", "YELLOW", "PURPLE"};
	private Random random;
	private String text;
	private String fontColor;
	private int score = 0;
	private int roundCount = 1;
	private EndGamePanel endGamePanel;

	public ColorGame(JPanel menu, JFrame hangMan, FileReader in, FileWriter out) {
		initComponents();
		setBounds(0,0,600,400);
		random = new Random();

		//Create EndGamePanel 
		endGamePanel = new EndGamePanel(menu, in, out);
		//Reference to hangMan JFrame
		hangMan.getContentPane().add(endGamePanel);
		//Hide EndGamePanel for now
		endGamePanel.setVisible(false);

		handleText();
	}
	//Change the text and color
	public void handleText() {
		
		if (roundCount >= 6) {
			roundCount = 1;
			endGamePanel();
			score = 0;
		}

		text = colors[random.nextInt(5)];
		jLabelTextColor.setText(text);
		switch (random.nextInt(5)) {
			case 0: {
				fontColor = "RED";
				jLabelTextColor.setForeground(Color.red);
				break;
			}
			case 1: {
				fontColor = "BLUE";
				jLabelTextColor.setForeground(Color.blue);
				break;
			}
			case 2: {
				fontColor = "YELLOW";
				jLabelTextColor.setForeground(Color.yellow);
				break;
			}
			case 3: {
				fontColor = "GREEN";
				jLabelTextColor.setForeground(Color.green);
				break;
			}
			case 4: {
				fontColor = "PURPLE";
				jLabelTextColor.setForeground(Color.magenta);
				break;
			}
		}
	}
	public void checkColor(String color) {
		if (fontColor.equals(color))
			score += 100;
	}
	public void endGamePanel() {
			//Set this PlayGame panel to not visibile
			this.setVisible(false);
			//Show the EndGamePanel
			endGamePanel.setVisible(true);
			//Set score
			endGamePanel.setScore(score);
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabelTextColor = new javax.swing.JLabel();
                jButtonRed = new javax.swing.JButton();
                jButtonGreen = new javax.swing.JButton();
                jButtonBlue = new javax.swing.JButton();
                jButtonPurple = new javax.swing.JButton();
                jButtonYellow = new javax.swing.JButton();

                setBackground(new java.awt.Color(0, 0, 0));
                setPreferredSize(new java.awt.Dimension(600, 400));

                jLabelTextColor.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
                jLabelTextColor.setForeground(new java.awt.Color(255, 255, 255));
                jLabelTextColor.setText("Color");

                jButtonRed.setBackground(new java.awt.Color(0, 0, 0));
                jButtonRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redCircle.png"))); // NOI18N
                jButtonRed.setLocation(new java.awt.Point(0, 0));
                jButtonRed.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRedActionPerformed(evt);
                        }
                });

                jButtonGreen.setBackground(new java.awt.Color(0, 0, 0));
                jButtonGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenCircle.png"))); // NOI18N
                jButtonGreen.setBounds(new java.awt.Rectangle(0, 0, 97, 29));
                jButtonGreen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonGreenActionPerformed(evt);
                        }
                });

                jButtonBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueCircle.png"))); // NOI18N
                jButtonBlue.setBounds(new java.awt.Rectangle(0, 0, 97, 29));
                jButtonBlue.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonBlueActionPerformed(evt);
                        }
                });

                jButtonPurple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purpleCircle.png"))); // NOI18N
                jButtonPurple.setLocation(new java.awt.Point(0, 0));
                jButtonPurple.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonPurpleActionPerformed(evt);
                        }
                });

                jButtonYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellowCircle.png"))); // NOI18N
                jButtonYellow.setBounds(new java.awt.Rectangle(0, 0, 97, 29));
                jButtonYellow.setLabel("");
                jButtonYellow.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonYellowActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                                .addComponent(jButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jButtonGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jButtonPurple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(251, 251, 251)
                                                .addComponent(jLabelTextColor)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(jButtonYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabelTextColor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonRed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonPurple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBlue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedActionPerformed
                // TODO add your handling code here:
		checkColor("RED");
		roundCount++;
		handleText();

        }//GEN-LAST:event_jButtonRedActionPerformed

        private void jButtonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreenActionPerformed
                // TODO add your handling code here:
		checkColor("GREEN");
		roundCount++;
		handleText();
        }//GEN-LAST:event_jButtonGreenActionPerformed

        private void jButtonPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurpleActionPerformed
                // TODO add your handling code here:
		checkColor("PURPLE");
		roundCount++;
		handleText();
        }//GEN-LAST:event_jButtonPurpleActionPerformed

        private void jButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlueActionPerformed
                // TODO add your handling code here:
		checkColor("BLUE");
		roundCount++;
		handleText();
        }//GEN-LAST:event_jButtonBlueActionPerformed

        private void jButtonYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYellowActionPerformed
                // TODO add your handling code here:
		checkColor("YELLOW");
		roundCount++;
		handleText();
		System.out.println(score);
        }//GEN-LAST:event_jButtonYellowActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonBlue;
        private javax.swing.JButton jButtonGreen;
        private javax.swing.JButton jButtonPurple;
        private javax.swing.JButton jButtonRed;
        private javax.swing.JButton jButtonYellow;
        private javax.swing.JLabel jLabelTextColor;
        // End of variables declaration//GEN-END:variables
}
