
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
fahad ahmed, reta yousif
cs 245
project 1.0
*/

public class EndGamePanel extends javax.swing.JPanel {

	/**
	 * Creates new form EndGamePanel
	 */
	private JFrame main;
	private JPanel menu;
	private BufferedReader br;
	private BufferedWriter bw;
	//private int scores[] = new int[5];
	//private ArrayList<String> names;
	//private ArrayList<Integer> values;
	//private Map playerScores = new HashMap();
	private String initials;
	private int score;
	//private int scoresIndex[] = new int[600];


	private ArrayList<Score> scores;

	public EndGamePanel(JFrame main, JPanel menu, BufferedReader br, BufferedWriter bw) {
		initComponents();
		setBounds(0,0,600,400);
		this.main = main;
		this.menu = menu;
		this.br = br;
		this.bw = bw;
		//read();
	}
	public void setScore(int score) {
		this.score = score;
		jLabel3.setText(String.valueOf(score));

		//Read file

		try {
			initialRead();
		} catch (IOException ex) {
			Logger.getLogger(EndGamePanel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	public void initialRead() throws IOException {
		scores = new ArrayList<Score>();

		String line = "";
		String lines[] = new String[2];
		br.mark(500);
		while (line != null) {
			line = br.readLine();
			if (line != null) {
				lines = line.split(" ");
				scores.add(new Score(lines[0], Integer.valueOf(lines[1])));
			}
		}
		br.reset();
		Collections.sort(scores, new Score());
		Collections.reverse(scores);
		inputHighScore();
	}
	
	public void appendToFile() throws IOException {
		scores.add(new Score(initials, score));
		//bw.write(initials + " " + score);
		Collections.sort(scores, new Score());
		Collections.reverse(scores);
		for (Score score : scores) {
			System.out.println(score.getName() + " " + score.getScore());
		}
	}
	
	public void writeToFile() throws IOException {
		//boolean inputUser = true;
		bw = new BufferedWriter(new FileWriter("highScores.txt", false));
		for (int i = 0; i < 6; i++ ) {
			bw.write(scores.get(i).getName()+ " " + score + "\n");
		}
		bw.flush();
	}

	public void inputHighScore() throws IOException {
		jLabelEnterInitials.setVisible(false);
		jTextFieldInitials.setVisible(false);
		if (score < scores.get(5).getScore()) 
			hideHighScoreComponents();
	}
	public void hideHighScoreComponents() {
		jLabelHighScore.setVisible(false);
		jButtonHSYes.setVisible(false);
		jButtonHSNo.setVisible(false);
		jLabelEnterInitials.setVisible(false);
		jTextFieldInitials.setVisible(false);
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jButtonEnd = new javax.swing.JButton();
                jLabelHighScore = new javax.swing.JLabel();
                jButtonHSYes = new javax.swing.JButton();
                jButtonHSNo = new javax.swing.JButton();
                jTextFieldInitials = new javax.swing.JTextField();
                jLabelEnterInitials = new javax.swing.JLabel();

                setBackground(new java.awt.Color(0, 0, 0));
                setPreferredSize(new java.awt.Dimension(600, 400));

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Game Over");

                jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Score: ");

                jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("0");

                jButtonEnd.setText("End");
                jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonEndActionPerformed(evt);
                        }
                });

                jLabelHighScore.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                jLabelHighScore.setForeground(new java.awt.Color(255, 255, 255));
                jLabelHighScore.setText("New HighScore! Save?");

                jButtonHSYes.setText("YES");
                jButtonHSYes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonHSYesActionPerformed(evt);
                        }
                });

                jButtonHSNo.setText("NO");
                jButtonHSNo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonHSNoActionPerformed(evt);
                        }
                });

                jTextFieldInitials.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldInitialsActionPerformed(evt);
                        }
                });

                jLabelEnterInitials.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
                jLabelEnterInitials.setForeground(new java.awt.Color(255, 255, 255));
                jLabelEnterInitials.setText("Enter Initials: ");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButtonEnd)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(204, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addGap(257, 257, 257))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(215, 215, 215))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelHighScore, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonHSYes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(122, 122, 122)
                                                                .addComponent(jButtonHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(167, 167, 167))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelEnterInitials)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldInitials, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(220, 220, 220))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jLabelHighScore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonHSYes)
                                        .addComponent(jButtonHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelEnterInitials)
                                        .addComponent(jTextFieldInitials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(jButtonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
                // TODO add your handling code here:
		this.setVisible(false);
		menu.setVisible(true);
        }//GEN-LAST:event_jButtonEndActionPerformed

        private void jTextFieldInitialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInitialsActionPerformed
		initials = jTextFieldInitials.getText();
		try {
			appendToFile();
			writeToFile();
			jTextFieldInitials.setEnabled(false);
		} catch (IOException ex) {
			Logger.getLogger(EndGamePanel.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_jTextFieldInitialsActionPerformed

        private void jButtonHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHSNoActionPerformed
                // TODO add your handling code here:
		this.setVisible(false);
		menu.setVisible(true);
        }//GEN-LAST:event_jButtonHSNoActionPerformed

        private void jButtonHSYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHSYesActionPerformed
                // TODO add your handling code here:
		jLabelEnterInitials.setVisible(true);
		jTextFieldInitials.setVisible(true);
        }//GEN-LAST:event_jButtonHSYesActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonEnd;
        private javax.swing.JButton jButtonHSNo;
        private javax.swing.JButton jButtonHSYes;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabelEnterInitials;
        private javax.swing.JLabel jLabelHighScore;
        private javax.swing.JTextField jTextFieldInitials;
        // End of variables declaration//GEN-END:variables
}
