
/*
fahad ahmed, reta yousif
cs 245
project 1.0
*/

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Timer;

public class HangMan extends javax.swing.JFrame {

	/**
	 * Creates new form HangMan
	 */
	private BufferedReader br;
	private BufferedWriter bw;
	
	public HangMan() {
		initComponents();
		setTitle("Hangman");
		setLocationRelativeTo(null);
		setSize(600, 400);
		getContentPane().setBackground(new java.awt.Color(0, 0, 0));
	}
	public void windowClosing(WindowEvent e) throws IOException {
		br.close();
		bw.close();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) throws FileNotFoundException, IOException {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		//Create main GUI window 
		HangMan hangMan = new HangMan();

		// Read and write from file
		FileReader in = new FileReader("highScores.txt");

		FileWriter out = new FileWriter("highScores.txt", true);

		BufferedReader br = new BufferedReader(in);
		BufferedWriter bw = new BufferedWriter(out);

		
		


		//Create splash screen
		SplashScreen splashScreen = new SplashScreen(); 
		hangMan.getContentPane().add(splashScreen);
		hangMan.pack();
		//Create Main menu
		MainMenu menu = new MainMenu();

		//Create ColorGame panel here
		ColorGame colorGame = new ColorGame(menu, hangMan, br, bw);
		hangMan.getContentPane().add(colorGame);
		colorGame.setVisible(false);

		//Create PlayGame screen
		//Temporary removal of hangman to jump to circleGame
		PlayGame playGame = new PlayGame(hangMan, menu, colorGame);
		hangMan.getContentPane().add(playGame);
		playGame.setVisible(false);

		//Create HighScores screen
		HighScores highScores = new HighScores();
		hangMan.getContentPane().add(highScores);
		highScores.setVisible(false);
		//Create Credits screen
		Credits credits = new Credits();
		hangMan.getContentPane().add(credits);
		credits.setVisible(false);


		//When the play button is clicked hide menu and show game.
		ActionListener playButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				playGame.resetGame();
				playGame.setVisible(true);

			}
		};
		//When the high scores button is clicked
		ActionListener hsButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				highScores.setVisible(true);
			}
		};
		//When the credits button is clicked
		ActionListener creditsButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				credits.setVisible(true);
			}
		};
		//When back button is clicked, go back to main menu
		ActionListener backButton = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				credits.setVisible(false);
				highScores.setVisible(false);
				menu.setVisible(true);
			}
		};


		menu.getPlayButton().addActionListener(playButtonClick);
		menu.getHighScoresButton().addActionListener(hsButtonClick);
		menu.getCreditsButton().addActionListener(creditsButtonClick);

		credits.getButton().addActionListener(backButton);
		highScores.getButton().addActionListener(backButton);
		
		
		//Create an event to remove the splash screen
		ActionListener taskPerformer = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				splashScreen.setVisible(false);
				hangMan.getContentPane().add(menu);
			}
		};
		//
		int delay = 3000; // 3 second delay
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//Display splash screen for 3 seconds
				hangMan.setVisible(true);
				new Timer(delay, taskPerformer).start();
			}
		});
	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
