
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahadahmed
 */
public class HangMan extends javax.swing.JFrame {

	/**
	 * Creates new form HangMan
	 */
	public HangMan() {
		initComponents();
		setTitle("Hangman");
		setLocationRelativeTo(null);
		getContentPane().setBackground(new java.awt.Color(0, 0, 0));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(600, 400));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HangMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		//Create main GUI window 
		HangMan hangMan = new HangMan();
		//Create splash screen
		SplashScreen splashScreen = new SplashScreen(); 
		hangMan.getContentPane().add(splashScreen);
		hangMan.pack();
		//Create Main menu
		MainMenu menu = new MainMenu();
		//Create PlayGame screen
		PlayGame playGame = new PlayGame();
		//Create HighScores screen
		HighScores highScores = new HighScores();
		//Create Credits screen
		Credits credits = new Credits();

		//When the play button is clicked hide menu and show game.
		ActionListener playButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				hangMan.getContentPane().add(playGame);
			}
		};
		//When the high scores button is clicked
		ActionListener hsButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				hangMan.getContentPane().add(highScores);
			}
		};
		//When the credits button is clicked
		ActionListener creditsButtonClick = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				menu.setVisible(false);
				hangMan.getContentPane().add(credits);
			}
		};

		menu.getPlayButton().addActionListener(playButtonClick);
		menu.getHighScoresButton().addActionListener(hsButtonClick);
		menu.getCreditsButton().addActionListener(creditsButtonClick);
		

		
		//Create an event to remove the splash screen
		ActionListener taskPerformer = new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				splashScreen.setVisible(false);
				hangMan.getContentPane().add(menu);
			}
		};
		//
		int delay = 3000; // 3 second delay
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//Display splash screen for 3 seconds
				hangMan.setVisible(true);
				new Timer(delay, taskPerformer).start();
			}
		});
	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
