/*
fahad ahmed, reta yousif
cs 245
project 1.0
*/
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahadahmed
 */
public class HighScores extends javax.swing.JPanel {

	/**
	 * Creates new form HighScores
	 */
	private FileReader in;
	private BufferedReader br;


	public HighScores() {
		initComponents();
		setBounds(0,0,600,400);
		//Read from highscores file and populate HighScores page
	}

	public void readAndPopulate() throws IOException {
		in = new FileReader("highScores.txt");
		br = new BufferedReader(in);
		//String line = "";
		String lines[] = new String[6];
		//String lines[] = new String[2];
		br.mark(500);
		for (int i = 0; i < lines.length; i++) {
			lines[i] = br.readLine();
		}
		br.reset();

		jLabel1Hs.setText(lines[0]);
		jLabel2Hs.setText(lines[1]);
		jLabel3Hs.setText(lines[2]);
		jLabel4Hs.setText(lines[3]);
		jLabel5Hs.setText(lines[4]);
		jLabel6Hs.setText(lines[5]);
		br.close();
	}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jLabel1Hs = new javax.swing.JLabel();
                jLabel2Hs = new javax.swing.JLabel();
                jLabel3Hs = new javax.swing.JLabel();
                jLabel4Hs = new javax.swing.JLabel();
                jLabel5Hs = new javax.swing.JLabel();
                jLabel6Hs = new javax.swing.JLabel();

                setBackground(new java.awt.Color(0, 0, 0));

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("HighScores");

                jButton1.setText("Back");
                jButton1.setLocation(new java.awt.Point(-32725, -32440));
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel1Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel1Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1Hs.setText("ABC.....00000");

                jLabel2Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel2Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2Hs.setText("ABC.....00000");

                jLabel3Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel3Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3Hs.setText("ABC.....00000");

                jLabel4Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel4Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4Hs.setText("ABC.....00000");

                jLabel5Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel5Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5Hs.setText("ABC.....00000");

                jLabel6Hs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel6Hs.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6Hs.setText("ABC.....00000");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(474, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6Hs)
                                                        .addComponent(jLabel5Hs)
                                                        .addComponent(jLabel4Hs)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel1Hs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel2Hs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel3Hs))))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(231, 231, 231))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(76, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1Hs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2Hs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3Hs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4Hs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5Hs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6Hs)
                                .addGap(57, 57, 57)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel1Hs;
        private javax.swing.JLabel jLabel2Hs;
        private javax.swing.JLabel jLabel3Hs;
        private javax.swing.JLabel jLabel4Hs;
        private javax.swing.JLabel jLabel5Hs;
        private javax.swing.JLabel jLabel6Hs;
        // End of variables declaration//GEN-END:variables

	public JButton getButton() {
		return jButton1;
	}
}
